create_user=create_user(?,?,?,?)
login=login(?,?,?,?,?)
addIncome=addIncome(?,?,?,?,?,?)
getIncome=getIncome(?,?,?)
addExpense=addExpense(?,?,?,?,?,?)
getExpenses=getExpenses(?,?,?)
create_savings_goal=create_savings_goal(?,?,?,?,?,?)
get_savings_goals=get_savings_goals(?)
add_savings_amount=add_savings_amount(?,?,?,?)
get_savings_overview=get_savings_overview(?)
get_financial_summary=get_financial_summary(?,?,?,?,?,?,?,?)
get_incExp_lastSix_months=get_incExp_lastSix_months(?,?,?,?)